# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['sunojump.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['PyQt6.QtMultimedia'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['runtime_hooks/freeze_support.py'],
    excludes=[
        '_distutils_hack',
        'IPython',
        'cupy',
        'lark',
        'matplotlib',
        'numba',
        'pandas',
        'playwright',
        'pytest',
        'scipy._lib.array_api_compat.cupy',
        'scipy._lib.array_api_compat.torch',
        'setuptools',
        'torch',
        'webview',
        'yt_dlp',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SunoJump',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    hide_console='hide-early',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
